name: Check Plugin PHP

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  lint-php:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Vérifier la syntaxe PHP du plugin
        run: |
          find plugins/ -name "*.php" -print0 | xargs -0 -n1 php -l
